[package]
name = "proximity-nameserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
rusqlite = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
